# -*- coding: utf-8 -*-
"""参考文献表。状态：A = 题名/作者/出处/年份已在线检索核对；B = 公式或超参数已对照参考实现；C = 通行引用，未逐条在线核对。"""
R = [
 ('capon', 'Capon, J. High-resolution frequency-wavenumber spectrum analysis. Proc. IEEE 57(8), 1969.', '2', 'A'),
 ('frost', 'Frost, O. L. An algorithm for linearly constrained adaptive array processing. Proc. IEEE 60(8), 1972.', '2', 'A'),
 ('gj', 'Griffiths, L. J., Jim, C. W. An alternative approach to linearly constrained adaptive beamforming. IEEE Trans. Antennas Propag. 30(1), 1982.', '2', 'A'),
 ('schmidt', 'Schmidt, R. O. Multiple emitter location and signal parameter estimation. IEEE Trans. Antennas Propag. 34(3), 1986.', '2', 'A'),
 ('kc', 'Knapp, C. H., Carter, G. C. The generalized correlation method for estimation of time delay. IEEE Trans. ASSP 24(4), 1976.', '2', 'A'),
 ('souden', 'Souden, M., Benesty, J., Affes, S. On optimal frequency-domain multichannel linear filtering for noise reduction. IEEE Trans. ASLP 18(2), 2010.', '2', 'A'),
 ('bmc', 'Benesty, J., Morgan, D. R., Cho, J. H. A new class of doubletalk detectors based on cross-correlation. IEEE Trans. Speech Audio Process. 8(2), 2000.', '3', 'A'),
 ('ev', 'Enzner, G., Vary, P. Frequency-domain adaptive Kalman filter for acoustic echo control in hands-free telephones. Signal Process. 86(6), 2006.', '3', 'A'),
 ('haykin', 'Haykin, S. Adaptive Filter Theory, 5th ed. Pearson, 2014.（NLMS、RLS 的收敛与失调分析）', '3, 19', 'C'),
 ('boll', 'Boll, S. F. Suppression of acoustic noise in speech using spectral subtraction. IEEE Trans. ASSP 27(2), 113–120, 1979。注：检索源之一把作者列为多人，本表按通行引用写作者为 Boll，页码与卷期与检索结果一致。', '4', 'A'),
 ('em84', 'Ephraim, Y., Malah, D. Speech enhancement using a minimum mean-square error short-time spectral amplitude estimator. IEEE Trans. ASSP 32(6), 1109–1121, 1984.', '4, 19', 'A'),
 ('em85', 'Ephraim, Y., Malah, D. Speech enhancement using a minimum mean-square error log-spectral amplitude estimator. IEEE Trans. ASSP 33(2), 443–445, 1985.', '4', 'A'),
 ('evt', 'Ephraim, Y., Van Trees, H. L. A signal subspace approach for speech enhancement. IEEE Trans. Speech Audio Process. 3(4), 251–266, 1995.', '4', 'C'),
 ('martin', 'Martin, R. Noise power spectral density estimation based on optimal smoothing and minimum statistics. IEEE Trans. Speech Audio Process. 9(5), 504–512, 2001.', '4', 'A'),
 ('cohen', 'Cohen, I. Noise spectrum estimation in adverse environments: improved minima controlled recursive averaging. IEEE Trans. Speech Audio Process. 11(5), 466–475, 2003.', '4', 'A'),
 ('wang18', 'Wang, D., Chen, J. Supervised speech separation based on deep learning: an overview. IEEE/ACM TASLP 26(10), 1702–1726, 2018.', '4', 'C'),
 ('erdogan', 'Erdogan, H., Hershey, J. R., Watanabe, S., Le Roux, J. Phase-sensitive and recognition-boosted speech separation using deep recurrent neural networks. ICASSP 2015.', '4', 'C'),
 ('kolbaek', 'Kolbæk, M., Yu, D., Tan, Z.-H., Jensen, J. Multitalker speech separation with utterance-level permutation invariant training. IEEE/ACM TASLP 25(10), 2017.', '4', 'C'),
 ('tasnet', 'Luo, Y., Mesgarani, N. Conv-TasNet: surpassing ideal time–frequency magnitude masking for speech separation. IEEE/ACM TASLP 27(8), 1256–1266, 2019.', '4, 23', 'A B'),
 ('dccrn', 'Hu, Y. et al. DCCRN: deep complex convolution recurrent network for phase-aware speech enhancement. Interspeech 2020, 2472–2476.', '4, 23', 'A B'),
 ('fsn', 'Hao, X., Su, X., Horaud, R., Li, X. FullSubNet: a full-band and sub-band fusion model for real-time single-channel speech enhancement. ICASSP 2021.', '4', 'A'),
 ('dfn2', 'Schröter, H., Escalante-B, A. N., Rosenkranz, T., Maier, A. DeepFilterNet2: towards real-time speech enhancement on embedded devices for full-band audio. IWAENC 2022.', '4, 23', 'A B'),
 ('sgmse', 'Richter, J., Welker, S., Lemercier, J.-M., Lay, B., Gerkmann, T. Speech enhancement and dereverberation with diffusion-based generative models. IEEE/ACM TASLP 31, 2351–2364, 2023.', '4', 'A'),
 ('wpe', 'Nakatani, T., Yoshioka, T., Kinoshita, K., Miyoshi, M., Juang, B.-H. Speech dereverberation based on variance-normalized delayed linear prediction. IEEE TASLP 18(7), 2010.', '5', 'C'),
 ('reynolds', 'Reynolds, D. A., Quatieri, T. F., Dunn, R. B. Speaker verification using adapted Gaussian mixture models. Digit. Signal Process. 10, 2000.', '5', 'C'),
 ('dehak', 'Dehak, N. et al. Front-end factor analysis for speaker verification. IEEE TASLP 19(4), 2011.', '5', 'C'),
 ('snyder', 'Snyder, D. et al. X-vectors: robust DNN embeddings for speaker recognition. ICASSP 2018.', '5', 'C'),
 ('ecapa', 'Desplanques, B., Thienpondt, J., Demuynck, K. ECAPA-TDNN: emphasized channel attention, propagation and aggregation in TDNN based speaker verification. Interspeech 2020.', '5, 23', 'A B'),
 ('arcface', 'Deng, J., Guo, J., Xue, N., Zafeiriou, S. ArcFace: additive angular margin loss for deep face recognition. CVPR 2019.', '5', 'C'),
 ('davis', 'Davis, S. B., Mermelstein, P. Comparison of parametric representations for monosyllabic word recognition. IEEE Trans. ASSP 28(4), 1980.', '6', 'C'),
 ('pcen', 'Wang, Y. et al. Trainable frontend for robust and far-field keyword spotting. ICASSP 2017.', '6', 'C'),
 ('specaug', 'Park, D. S. et al. SpecAugment: a simple data augmentation method for automatic speech recognition. Interspeech 2019.', '6', 'C'),
 ('rabiner', 'Rabiner, L. R. A tutorial on hidden Markov models and selected applications in speech recognition. Proc. IEEE 77(2), 257–286, 1989.', '7, 19', 'C'),
 ('hinton', 'Hinton, G. et al. Deep neural networks for acoustic modeling in speech recognition. IEEE Signal Process. Mag. 29(6), 2012.', '7', 'C'),
 ('ctc', 'Graves, A., Fernández, S., Gomez, F., Schmidhuber, J. Connectionist temporal classification: labelling unsegmented sequence data with recurrent neural networks. ICML 2006, 369–376.', '7, 19', 'A'),
 ('rnnt', 'Graves, A. Sequence transduction with recurrent neural networks. arXiv:1211.3711, 2012.', '7, 23', 'B C'),
 ('lfmmi', 'Povey, D. et al. Purely sequence-trained neural networks for ASR based on lattice-free MMI. Interspeech 2016.', '7', 'C'),
 ('vaswani', 'Vaswani, A. et al. Attention is all you need. NeurIPS 2017.', '7, 19', 'C'),
 ('conformer', 'Gulati, A. et al. Conformer: convolution-augmented Transformer for speech recognition. Interspeech 2020. arXiv:2005.08100.', '7, 23', 'A B'),
 ('w2v2', 'Baevski, A., Zhou, Y., Mohamed, A., Auli, M. wav2vec 2.0: a framework for self-supervised learning of speech representations. NeurIPS 2020.', '7, 23', 'A B'),
 ('hubert', 'Hsu, W.-N. et al. HuBERT: self-supervised speech representation learning by masked prediction of hidden units. IEEE/ACM TASLP 29, 2021.', '7', 'A'),
 ('whisper', 'Radford, A. et al. Robust speech recognition via large-scale weak supervision. ICML 2023.', '7', 'C'),
 ('kn', 'Kneser, R., Ney, H. Improved backing-off for m-gram language modeling. ICASSP 1995.', '8', 'C'),
 ('cg', 'Chen, S. F., Goodman, J. An empirical study of smoothing techniques for language modeling. Comput. Speech Lang. 13(4), 1999.', '8', 'C'),
 ('mohri', 'Mohri, M., Pereira, F., Riley, M. Weighted finite-state transducers in speech recognition. Comput. Speech Lang. 16(1), 2002.', '8', 'C'),
 ('mwer', 'Prabhavalkar, R. et al. Minimum word error rate training for attention-based sequence-to-sequence models. ICASSP 2018.', '8', 'C'),
 ('hb', 'Hunt, A. J., Black, A. W. Unit selection in a concatenative speech synthesis system using a large speech database. ICASSP 1996.', '10, 11', 'C'),
 ('mlpg', 'Tokuda, K. et al. Speech parameter generation algorithms for HMM-based speech synthesis. ICASSP 2000.', '11', 'C'),
 ('tacotron2', 'Shen, J. et al. Natural TTS synthesis by conditioning WaveNet on mel spectrogram predictions. ICASSP 2018.', '11', 'C'),
 ('fs2', 'Ren, Y. et al. FastSpeech 2: fast and high-quality end-to-end text to speech. ICLR 2021.', '11, 23', 'C'),
 ('vits', 'Kim, J., Kong, J., Son, J. Conditional variational autoencoder with adversarial learning for end-to-end text-to-speech. ICML 2021.', '11', 'A'),
 ('ddpm', 'Ho, J., Jain, A., Abbeel, P. Denoising diffusion probabilistic models. NeurIPS 2020.', '11, 19', 'C'),
 ('cfm', 'Lipman, Y., Chen, R. T. Q., Ben-Hamu, H., Nickel, M., Le, M. Flow matching for generative modeling. ICLR 2023. arXiv:2210.02747.', '11, 19, 23', 'A'),
 ('cfg', 'Ho, J., Salimans, T. Classifier-free diffusion guidance. NeurIPS Workshop 2021.', '11', 'C'),
 ('wavenet', 'van den Oord, A. et al. WaveNet: a generative model for raw audio. arXiv:1609.03499, 2016.', '12', 'C'),
 ('lpcnet', 'Valin, J.-M., Skoglund, J. LPCNet: improving neural speech synthesis through linear prediction. ICASSP 2019.', '12', 'C'),
 ('gl', 'Griffin, D. W., Lim, J. S. Signal estimation from modified short-time Fourier transform. IEEE Trans. ASSP 32(2), 1984.', '12', 'C'),
 ('gan', 'Goodfellow, I. et al. Generative adversarial nets. NeurIPS 2014.', '12, 19', 'C'),
 ('lsgan', 'Mao, X. et al. Least squares generative adversarial networks. ICCV 2017.', '12, 19', 'C'),
 ('hifigan', 'Kong, J., Kim, J., Bae, J. HiFi-GAN: generative adversarial networks for efficient and high fidelity speech synthesis. NeurIPS 2020.', '12, 23', 'A B'),
 ('soundstream', 'Zeghidour, N. et al. SoundStream: an end-to-end neural audio codec. IEEE/ACM TASLP 30, 495–507, 2022.', '12', 'A'),
 ('encodec', 'Défossez, A., Copet, J., Synnaeve, G., Adi, Y. High fidelity neural audio compression. arXiv:2210.13438, 2022.', '12, 23', 'A B'),
 ('schreier', 'Schreier, R., Temes, G. C. Understanding Delta-Sigma Data Converters. Wiley–IEEE Press, 2005.', '16', 'C'),
 ('ramjee', 'Ramjee, R., Kurose, J., Towsley, D., Schulzrinne, H. Adaptive playout mechanisms for packetized audio applications in wide-area networks. IEEE INFOCOM 1994.', '18', 'C'),
 ('opus', 'Valin, J.-M., Vos, K., Terriberry, T. Definition of the Opus audio codec. IETF RFC 6716, 2012.', '18', 'A'),
 ('pesq', 'Rix, A. W., Beerends, J. G., Hollier, M. P., Hekstra, A. P. Perceptual evaluation of speech quality (PESQ) — a new method for speech quality assessment of telephone networks and codecs. ICASSP 2001, 749–752.', '20', 'A B'),
 ('p862', 'ITU-T Rec. P.862 (2001) PESQ；P.862.1 (2003) 到 MOS-LQO 的映射；P.862.2 (2007) 宽带扩展。', '20', 'B'),
 ('stoi', 'Taal, C. H., Hendriks, R. C., Heusdens, R., Jensen, J. An algorithm for intelligibility prediction of time–frequency weighted noisy speech. IEEE TASLP 19(7), 2125–2136, 2011.', '20', 'A B'),
 ('sisdr', 'Le Roux, J., Wisdom, S., Erdogan, H., Hershey, J. R. SDR — half-baked or well done? ICASSP 2019, 626–630.', '20', 'A'),
 ('bs1534', 'ITU-R BS.1534 (MUSHRA)；ITU-T P.800 (MOS)。', '13, 20', 'C'),
]
D = dict((r[0], r) for r in R)
IDX = dict((r[0], i + 1) for i, r in enumerate(R))

# 各节"依据的文献"
CITES = {
 'u2': ['capon', 'frost', 'gj', 'schmidt', 'kc', 'souden'],
 'u3': ['haykin', 'bmc', 'ev'],
 'u4': ['boll', 'em84', 'em85', 'evt', 'martin', 'cohen', 'wang18', 'erdogan', 'kolbaek', 'tasnet', 'dccrn', 'fsn', 'dfn2', 'sgmse'],
 'u5': ['wpe', 'reynolds', 'dehak', 'snyder', 'ecapa', 'arcface'],
 'u6': ['davis', 'pcen', 'specaug'],
 'u7': ['rabiner', 'hinton', 'ctc', 'rnnt', 'lfmmi', 'vaswani', 'conformer', 'w2v2', 'hubert', 'whisper'],
 'u8': ['kn', 'cg', 'mohri', 'mwer'],
 'u10': ['hb'],
 'u11': ['hb', 'mlpg', 'tacotron2', 'fs2', 'vits', 'ddpm', 'cfm', 'cfg'],
 'u12': ['wavenet', 'lpcnet', 'gl', 'gan', 'lsgan', 'hifigan', 'soundstream', 'encodec'],
 'u13': ['bs1534'],
 'u17': ['schreier'],
 'u19': ['ramjee', 'opus'],
 'u20': ['haykin', 'ev', 'em84', 'rabiner', 'ctc', 'vaswani', 'gan', 'lsgan', 'ddpm', 'cfm'],
 'u21': ['pesq', 'p862', 'stoi', 'sisdr', 'bs1534'],
}
